# Generated by Django 3.2 on 2021-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_platform'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.Game'),
        ),
    ]
