# Generated by Django 3.2 on 2021-04-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XB', 'Xbox'), ('NI', 'Nintendo')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
